### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by lucasjinreal** [zhengli97/OKDHP#1]
pretrained models?

**Comment by zhengli97** [comment]
Models will be released in the future (probably in June). You can leave your email here and I will let you know.

**Comment by lalala531** [comment]
> Models will be released in the future (probably in June). You can leave your email here and I will let you know.

由于训练模型吗

**Comment by lalala531** [comment]
> Models will be released in the future (probably in June). You can leave your email here and I will let you know.

有预训练模型吗

**Comment by zhengli97** [comment]
抱歉 时间已经间隔好久了 把这些事儿都忘了 时隔一年半 这段时间因为变换了好几个地方 所以以前训练留下来的模型文件已经没有了 不好意思啦 可能需要你自己去训练了
