### ISSUE TITLE
How to achieve the score of MPII test and val which were displayed in your paper?

### ISSUE THREAD

**Issue by tt1234562** [zhengli97/OKDHP#2]
Dear researchers, I would like to follow your work, but I can not get the score as described in the table1 and table2 of your paper. Could you teach me the details of training？Thanks :)

**Comment by zhengli97** [comment]
What is your score?
Here are the settings I used to achieve 90.034 on the MPII validation set.

Head    | Sho.    | Elb.      | Wri.     | Hip      | Knee    | Ank.    | Mean
97.003 | 96.111 | 90.864 | 85.953 | 89.527 | 85.412 | 81.696 | 90.034

For a 4-Stack OKDHP with three branches, we set alpha=1 and beta=2 in Eqn.8. Each branch has two shared and two individual HG modules. LR schedule: [0, 90, 120, 150], LR: 2.5e-4. 
Different experimental environments may lead to different results. Try to run more times.
