### ISSUE TITLE
关于Student Helping Teacher: Teacher Evolution via Self-Knowledge Distillation

### ISSUE THREAD

**Issue by Kea1b0Om** [zhengli97/OKDHP#3]
您好!您的Student Helping Teacher: Teacher Evolution via Self-Knowledge Distillation这篇论文的代码方便分享吗

**Comment by Kea1b0Om** [comment]
2635189351@qq.com

**Comment by zhengli97** [comment]
你好，谢谢你的关注，这篇paper被拒了，我已经改了论文重新投稿了。论文中了之后会release代码的。

**Comment by Kea1b0Om** [comment]
谢谢回复 预祝您发更好的paper

**Comment by Kea1b0Om** [comment]
您好！我大致复现了您的论文 我发现feature_loss 在25个step后就不在下降 反而开始上升 ，您能帮我分析一下原因吗

**Comment by zhengli97** [comment]
你复现论文是有什么特殊的需要吗？作为对比方法？

**Comment by Kea1b0Om** [comment]
嗯 另外一个就是感觉您这篇论文效果挺好的，所以想尝试复现一下，结果我的精度最高只到了78.92，不知道为什么

**Comment by zhengli97** [comment]
我已经把我的repo给reopen了，https://github.com/zhengli427/TESKD， 在这里去找你想要的实现结果吧

**Comment by Kea1b0Om** [comment]
感谢感谢！！！

**Comment by Kea1b0Om** [comment]
您好！想请教您一个问题， 我找到了Be Your Own Teacher: Improve the Performance of Convolutional Neural Networks via Self Distillation这片论文的源代码 ，在代码中它使用了更多的数据增强来达到实验的效果，而没有做消融实验，这在知识蒸馏中是可行的吗

**Comment by zhengli97** [comment]
额外加aug的方法是不标准的，在进行实验对比中都要对aug进行统一。

**Comment by LinEvol** [comment]
您好!您的Student Helping Teacher: Teacher Evolution via Self-Knowledge Distillation这篇论文的代码方便分享吗?
842945896@qq.com

**Comment by zhengli97** [comment]
> 您好!您的Student Helping Teacher: Teacher Evolution via Self-Knowledge Distillation这篇论文的代码方便分享吗? [842945896@qq.com](mailto:842945896@qq.com)

谢谢关注 我明天有空发给你

**Comment by zhengli97** [comment]
@LinEvol 我已经发过去啦 请查收一下哈~
