### ISSUE TITLE
請問 branch0 結果

### ISSUE THREAD

**Issue by n26092043** [zhengli97/OKDHP#7]
您好
單純用 hg_template.yaml 訓練
印出來的結果中有 branch0, 1, 2, 3
想請問 branch0 代表的是論文中前兩個 share stacks 對嗎?
如果是的話，另外想請問 branch0 的 acc 始終高於後面的三個 branches，這樣的結果是正常的嗎?
謝謝

**Comment by zhengli97** [comment]
branch 0的结果是三个分支结果带权ensemble结果。所以是会比后面三个branch的结果要高的。

**Comment by zhengli97** [comment]
如果没有其他的问题我就关闭这个issue啦~ 有问题请联系zhengli97@mail.nankai.edu.cn
